---
output:
  html_document:
    theme: readable
    df_print: paged
    highlight: tango
---

```{r setup, include=FALSE}
# do not change this chunk
knitr::opts_chunk$set(echo=T, eval=T, fig.width=6, fig.height=4, warning=F, message=F )
```

# Spring 2021 Exam Answers
**PAF 573**

**YOUR NAME**  

# Load data  
```{r}
# data for Question 1
URLQ1 <- "https://raw.githubusercontent.com/spiromar/files/main/paf573/hc_exp.csv"
q1data <- read.csv( URLQ1 )

# data for Question 2
URLQ2 <- "https://raw.githubusercontent.com/spiromar/files/main/paf573/hc_2012-13.csv"
q2data <- read.csv( URLQ2 )

```


# Question 1  
## A.
```{r}
# show relevant work here if needed

```

**ANSWER**  

## B.
```{r}
# show relevant work here if needed

```

**ANSWER**  

## C.
```{r}
# show relevant work here if needed

```

**ANSWER**  

## D.
```{r}
# show relevant work here if needed

```

**ANSWER**  

## E.
```{r}
# show relevant work here if needed

```

**ANSWER**  



# Question 2  
## A.
```{r}
# show relevant work here if needed

```

**ANSWER**  

## B.
```{r}
# show relevant work here if needed

```

**ANSWER**  

## C.
```{r}
# show relevant work here if needed

```

**ANSWER**  

## D.
```{r}
# show relevant work here if needed

```

**ANSWER**  

